language: php
php:
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
env:
  - COMPOSER_COMMAND=install
  - COMPOSER_COMMAND=update
install: composer $COMPOSER_COMMAND
